apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-monorepo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app-monorepo
  namespace: mae
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: testing_pipeline_params
    value:
      testing-sub-path: "./tanzu-java-web-app"
  source:
    git:
      url: ssh://git@github.com/Mpluya/application-accelerator-samples
      ref:
        branch: main
    subPath: tanzu-java-web-app